POST http://{{host}}:{{port}}/developer
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "toni@karumi.com",
  "username": "tonilopezmr",
  "password": "1234"
}

> {%
 client.global.set("devId", response.body.id)
 %}

###

GET http://{{host}}:{{port}}/developer/{{devId}}
Accept: application/json
Authorization: Bearer {{token}}

###


GET http://{{host}}:{{port}}/developer/ba166a3c-f9ce-414c-baad-1737038d49b2
Accept: application/json
Authorization: Bearer {{token}}

###
